### ISSUE TITLE
Ejercicios 

### ISSUE THREAD

**Issue by LuisAlexisMorales** [SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-equipo-6#1]
[ejercicios.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-equipo-6/files/12827002/ejercicios.pdf)

**Comment by Maritza2893** [comment]
Portada: 25%
Procedimiento:  15% (falta de ejercicios y mal resultados)
Figuras: 17% (falta la descripción de imágenes) 
Resultados y conclusiones: 20%
Total: 15.4%
Evaluado por Maritza
